#pragma once

#define WND_PARAM_X		500
#define WND_PARAM_Y		0
#define WND_PARAM_WIDTH	396
#define WND_PARAM_HEIGH	589
#define WND_PARAM_TITLE "*飞机大战*"

#define BACKGOUND_MAPSIZE_WIDTH	 380
#define BACKGOUND_MAPSIZE_HEIGH	 550

#define PALYERPLANE_SIZE_WIDTH	60	
#define PALYERPLANE_SIZE_HEIGH	60

#define GUNNER_SIZE_WIDTH	6
#define GUNNER_SIZE_HEIGH	9

#define TIMER_BACKGROUND_MOVE_ID			1
#define TIMER_BACKGROUND_MOVE_FREQUENCY_MS	200

#define PLAYERPLANE_MOVE_STEP				4
#define TIMER_PLAYERPLANE_MOVE_ID			2
#define TIMER_PLAYERPLANE_MOVE_FREQUENCY_MS	20

#define GUNNER_MOVE_STEP				8
#define TIMER_GUNNER_MOVE_ID			3
#define TIMER_GUNNER_MOVE_FREQUENCY_MS	100
#define TIMER_GUNNER_SEND_ID			4
#define TIMER_GUNNER_SEND_FREQUENCY_MS	800

#define FOEPLANE_SMALL_BLOOD		2
#define FOEPLANE_MIDDLE_BLOOD		6
#define FOEPLANE_BIG_BLOOD			10

#define GUNNER_HURT_BLOOD			2

#define FOEPLANE_SMALL_SIZE_WEIGH	34
#define FOEPLANE_SMALL_SIZE_HEIGH	28
#define FOEPLANE_MIDDLE_SIZE_WEIGH	70
#define FOEPLANE_MIDDLE_SIZE_HEIGH	90
#define FOEPLANE_BIG_SIZE_WEIGH		108
#define FOEPLANE_BIG_SIZE_HEIGH		129

#define FOEPLANE_SMALL_STEP						14
#define TIMER_SMALLFOE_CREATE_ID				5	
#define TIMER_SMALLFOE_CREATE_FREQUENCY_MS		6000

#define FOEPLANE_MIDDLE_STEP					9
#define TIMER_MIDDLEFOE_CREATE_ID				6
#define TIMER_MIDDLEFOE_CREATE_FREQUENCY_MS		9000

#define FOEPLANE_BIG_STEP						5
#define TIMER_BIGFOE_CREATE_ID					7
#define TIMER_BIGFOE_CREATE_FREQUENCY_MS		12000

#define TIMER_FOEPLANE_MOVE_ID					8
#define TIMER_FOEPLANE_MOVE_FREQUENCY_MS		80

//定时检查敌人飞机是否撞击炮弹及玩家飞机
#define TIMER_CHEAK_ISHIT_ID					9
#define TIMER_CHEAK_ISHIT_FREQUENCY_MS			20

//定时切换敌人飞机爆炸效果
#define TIMER_BOOMPLANE_CHANGE_ID				10
#define TIMER_BOOMPLANE_FREQUENCY_MS			400